=head1 NAME

Time::Monotonic - Monotonic time

=head1 SYNOPSIS

    use Time::Monotonic qw[timemono];
    $t = timemono();
    

=head1 DESCRIPTION

=head1 FUNCTIONS

=head2 timemono
    
    $time = timemono();
    
=head1 AUTHOR

Christian Hansen C<chansen@cpan.org>

=head1 COPYRIGHT

Copyright 2013 by Christian Hansen.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

